-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."product_variant" add column "product_id" serial
--  not null unique;
